version: '3'

tasks:
  setup:
    desc: Setup Docusaurus locally
    cmds:
      - yarn install

  default:
    desc: Start website
    aliases: [s, start]
    vars:
      HOST: '{{default "localhost" .HOST}}'
      PORT: '{{default "3001" .PORT}}'
    cmds:
      - npx docusaurus start --no-open --host={{.HOST}} --port={{.PORT}}

  build:
    desc: Build website
    cmds:
      - npx docusaurus build

  clean:
    desc: Clean temp directories
    cmds:
      - rm -rf ./build

  deploy:
    desc: Build and deploy Docusaurus
    summary: Requires GIT_USER and GIT_PASS envs to be previous set
    cmds:
      - npx docusaurus deploy
